Repository sprintPart3Team4/the-julge, pull requests merged in 2024-01, with the labels that each got.

#31 Feat: 사장님 - 공고상세 - 타이틀 UI 컴포넌트 구현
  components/shopNoticePage/contentsTitle/Category.tsx
  components/shopNoticePage/contentsTitle/ContentsTitle.tsx
  components/shopNoticePage/contentsTitle/Title.tsx
Labels: 디자인, 사장님

#36 Feat: 사장님/공고상세 - 공고 내용 보여주는 컴포넌트 UI 구현
  components/shopNoticePage/noticeContents/Address.tsx
  components/shopNoticePage/noticeContents/HourlyPay.tsx
  components/shopNoticePage/noticeContents/HourlyPayBadge.tsx
  components/shopNoticePage/noticeContents/Panel.tsx
  components/shopNoticePage/noticeContents/ShopDescription.tsx
  components/shopNoticePage/noticeContents/Thumbnail.tsx
  components/shopNoticePage/noticeContents/WorkHour.tsx
Labels: 디자인, 사장님

#37 Feat: 사장님/가게정보상세 - 컴포넌트 UI 구현
  components/shop/myShopProfile/MyShopProfile.module.scss
  components/shop/myShopProfile/MyShopProfile.tsx
  components/shop/noticeCard/NoticeCard.module.scss
  components/shop/noticeCard/NoticeCard.tsx
  components/shop/noticeSuggestion/NoticeSuggestion.module.scss
  components/shop/noticeSuggestion/NoticeSuggestion.tsx
  package-lock.json
  package.json
  pages/api/mockdata.ts
  pages/shop/index.tsx
  public/images/shop-sample.png
  styles/normalize.scss
Labels: 디자인, 사장님

#45 Design: 사장님/가게정보등록 반응형 UI 구현
  components/register/shopInfo/shopInfoForm/shopInfoForm.module.scss
  components/register/shopInfo/shopInfoTitle/ShopInfoTitle.module.scss
Labels: 디자인, 사장님

#48 Design: 사장님/가게정보상세 반응형 컴포넌트
  components/shop/myShopProfile/MyShopProfile.module.scss
  components/shop/myShopProfile/MyShopProfile.tsx
  components/shop/noticeCard/NoticeCard.module.scss
  components/shop/noticeCard/NoticeCard.tsx
  components/shop/noticeSuggestion/NoticeSuggestion.module.scss
  components/shop/shopPageLayout/ShopPageLayout.module.scss
  components/shop/shopPageLayout/ShopPageLayout.tsx
  pages/_document.tsx
  pages/shop/index.tsx
Labels: 디자인, 사장님

#42 feat : 로그인/반응형 UI 구현
  components/common/logo/Logo.module.scss
  components/sign/input/input.module.scss
  components/sign/input/input.tsx
  components/sign/signBotton/SignBottom.module.scss
  components/sign/signBotton/SignBotton.tsx
  components/sign/signButton/SignButton.module.scss
  components/sign/signButton/SignButton.tsx
  components/sign/signLayout/SignLayout.module.scss
  components/sign/signLayout/SignLayout.tsx
Labels: 디자인, 로그인

#58 Feat: 공통 버튼 컴포넌트
  components/common/button/Button.module.scss
  components/common/button/Button.tsx
  components/common/checkButton/CheckButton.tsx
  styles/variables.scss
Labels: 기능, 디자인, 공통

#54 Design: 공통/Footer - css 수정, email 링크 추가
  components/common/footer/Footer.module.scss
  components/common/footer/Footer.tsx
Labels: 디자인, 공통

#53 Feat: 사장님/가게정보등록-셀렉트박스기능구현
  components/register/shopInfo/shopInfoForm/SelectBox.tsx
  components/register/shopInfo/shopInfoForm/shopInfoForm.module.scss
Labels: 기능, 사장님

#57 Design: 사장님/가게정보상세 - 레이아웃 안에서 컴포넌트 반응형
  components/shop/myShopProfile/MyShopProfile.module.scss
  components/shop/myShopProfile/MyShopProfile.tsx
  components/shop/noticeCard/NoticeCard.module.scss
  components/shop/noticeCard/NoticeCard.tsx
  components/shop/noticeCardList/NoticeCardList.module.scss
  components/shop/noticeCardList/NoticeCardList.tsx
  components/shop/noticeSuggestion/NoticeSuggestion.module.scss
  components/shop/noticeSuggestion/NoticeSuggestion.tsx
  components/shop/shopPageLayout/ShopPageLayout.module.scss
  components/shop/shopPageLayout/ShopPageLayout.tsx
  pages/shop/index.tsx
Labels: 디자인, 사장님

#49 feat : 로그인/회원가입 회원유형 컴포넌트 구현
  components/sign/userType/UserType.module.scss
  components/sign/userType/UserType.tsx
  public/images/unCheck.svg
Labels: 디자인, 로그인

#62 Feat: 공통/모달 컴포넌트
  components/common/modal/Modal.module.scss
  components/common/modal/Modal.tsx
  components/common/modal/confirmModal/ConfirmModal.module.scss
  components/common/modal/confirmModal/ConfirmModal.tsx
  components/common/modal/warningModal/WarningModal.module.scss
  components/common/modal/warningModal/WarningModal.tsx
  components/common/modal/yesOrNoModal/YesOrNoModal.module.scss
  components/common/modal/yesOrNoModal/YesOrNoModal.tsx
  styles/variables.scss
Labels: 기능, 디자인, 공통

#63 사장님/가게정보상세-레이아웃
  components/common/button/Button.module.scss
  components/common/footer/Footer.module.scss
  components/shop/myShopProfile/MyShopProfile.module.scss
  components/shop/myShopProfile/MyShopProfile.tsx
  components/shop/noticeCard/NoticeCard.module.scss
  components/shop/noticeCard/NoticeCard.tsx
  components/shop/noticeSuggestion/NoticeSuggestion.tsx
  components/shop/registerSuggestion/RegisterSuggestion.module.scss
  components/shop/registerSuggestion/RegisterSuggestion.tsx
  components/shop/registerSuggestion/constant.js
  components/shop/shopPageLayout/ShopPageLayout.module.scss
  components/shop/shopPageLayout/ShopPageLayout.tsx
  pages/shop/index.tsx
Labels: 디자인, 사장님

#67 Feat: 사장님/가게정보등록 - 파일 인풋 기능 구현
  components/register/shopInfo/shopInfoForm/FileInput.tsx
  components/register/shopInfo/shopInfoForm/api.ts
  components/register/shopInfo/shopInfoForm/shopInfoForm.module.scss
Labels: 기능, 사장님
