Repository sprintPart3Team4/the-julge, pull requests merged in 2024-02, with the labels that each got.

#71 feat : 로그인/로그인-레이아웃
  components/sign/signinForm/SigninForm.module.scss
  components/sign/signinForm/SigninForm.tsx
  pages/signin.tsx
Labels: 디자인, 로그인

#73 feat : 로그인/회원가입-레이아웃
  components/sign/signupForm/SignupForm.module.scss
  components/sign/signupForm/SignupForm.tsx
  pages/signup.tsx
Labels: 디자인, 로그인

#75 로그인/회원가입 가입과에러
  components/sign/signupForm/SignupForm.module.scss
  components/sign/signupForm/SignupForm.tsx
Labels: 기능, 로그인

#78 로그인/로그인 쿠키
  components/sign/signinForm/SigninForm.tsx
Labels: 기능, 로그인

#80 로그인/로그인 에러모달
  components/sign/signinForm/signinForm.tsx
Labels: 기능, 로그인

#81 Feat: 사장님/가게정보상세 - 공고 카드 데이터 적용 및 무한 스크롤 구현
  components/shop/noticeCard/NoticeCard.module.scss
  components/shop/noticeCard/NoticeCard.tsx
  components/shop/noticeCardList/NoticeCardList.tsx
  hooks/useGetNoticeList.ts
  next.config.mjs
Labels: 기능, 사장님

#88 사장님/공고등록 API 테스트
  components/common/button/closeButton/CloseButton.module.scss
  components/common/button/closeButton/CloseButton.tsx
  components/common/closeButton/CloseButton.module.scss
  components/common/closeButton/CloseButton.tsx
  components/common/input/Input.module.scss
  components/common/input/Input.tsx
  components/common/titleBox/TitleBox.module.scss
  components/common/titleBox/TitleBox.tsx
  components/register/notice/NoticeRegister/EditNotice.module.scss
  components/register/notice/NoticeRegister/EditNotice.tsx
  components/register/notice/NoticeRegister/NoticeRegister.module.scss
  components/register/notice/NoticeRegister/NoticeRegister.tsx
  components/register/notice/NoticeRegister/useEditNotice.ts
  components/register/notice/NoticeRegister/usePostNotice.ts
  components/register/notice/NoticeRegister/useReloadNotice.ts
  components/register/shopInfo/shopInfoForm/Input.tsx
  components/register/shopInfo/shopInfoForm/shopInfoForm.tsx
  components/shop/myShopProfile/MyShopProfile.tsx
  components/shop/shopPageLayout/ShopPageLayout.tsx
  pages/index.tsx
  pages/shop/index.tsx
  test,.http
  tsconfig.json
Labels: 기능, 디자인, 사장님, 수정중

#91 Desgin: 사장님/가게정보상세-UI 수정 (시급 인상 배지 및 일시 포맷)
  components/shop/noticeCard/NoticeCard.tsx
  components/shopNoticePage/highPayRateBadge/HighPayRateBadge.module.scss
  components/shopNoticePage/highPayRateBadge/HighPayRateBadge.tsx
  lib/getFullDate.ts
  package-lock.json
  package.json
  public/images/arrow-up-bold-grey.svg
  public/images/arrow-up-bold-red20.svg
  public/images/arrow-up-bold-red30.svg
  public/images/arrow-up-bold-red40.svg
  public/images/arrow-up-bold-white.svg
Labels: 디자인, 사장님

#90 Feat: 공통/셀렉트박스 구현
  components/common/selectBox/SelectBox.module.scss
  components/common/selectBox/SelectBox.tsx
  components/common/selectBox/SelectBox_example.tsx
Labels: 사장님, 공통

#94 Feat: 공통/textarea 구현
  components/common/textarea/Textarea.module.scss
  components/common/textarea/Textarea.tsx
Labels: 사장님, 공통

#92 Feat: 사장님/가게정보상세-내 가게 컴포넌트 받아온 데이터 UI에 반영
  components/shop/myShopProfile/MyShopProfile.module.scss
  components/shop/myShopProfile/MyShopProfile.tsx
  components/shop/noticeCard/NoticeCard.tsx
  components/shop/noticeCardList/NoticeCardList.tsx
Labels: 기능, 사장님

#96 Design: 공통/네비게이션 바-UI 구현 및 전역으로 추가
  components/common/navBar/NavBar.module.scss
  components/common/navBar/NavBar.tsx
  pages/_app.tsx
  styles/global.scss
Labels: 디자인, 공통

#101 Feat: 신청자 목록 구현
  components/shopNoticePage/applications/Application.tsx
  components/shopNoticePage/applications/Applications.module.scss
  components/shopNoticePage/applications/Applications.tsx
  components/shopNoticePage/statusBadge/StatusBadge.tsx
  components/shopNoticePage/statusBadge/statusBadge.module.scss
  components/shopNoticePage/statusButton/StatusButton.module.scss
  components/shopNoticePage/statusButton/StatusButton.tsx
  pages/shop/[id].tsx
Labels: 기능, 디자인, 사장님

#109 Feat: 공통/gnb-검색 기능 구현
  components/common/navBar/NavBar.tsx
  components/noticeList/NoticeList.tsx
  components/noticeList/noticeCardList/NoticeCardList.module.scss
  components/noticeList/noticeCardList/NoticeCardList.tsx
  components/noticeList/noticeListLayout/NoticeListLayout.module.scss
  components/noticeList/noticeListLayout/NoticeListLayout.tsx
  components/shop/noticeCardList/NoticeCardList.tsx
  components/shop/shopPageLayout/ShopPageLayout.tsx
  pages/_app.tsx
  pages/index.tsx
Labels: 기능, 알바님

#110 Feat: 공통/gnb-로그인 여부에 따른 버튼 및 토글 기능
  components/common/navBar/NavBar.module.scss
  components/common/navBar/NavBar.tsx
  components/common/navBar/notificationList/NotificationList.module.scss
  components/common/navBar/notificationList/NotificationList.tsx
Labels: 기능, 공통

#119 Design: 알바님/공고리스트 UI
  components/Notices/Notices.module.scss
  components/Notices/Notices.tsx
  pages/index.tsx
  pages/search/index.tsx
Labels: 디자인, 알바님

#118 Feat: 상세필터 UI 수정
  components/Notices/filterDropBox/filterAddress/FilterAddress.module.scss
  components/Notices/filterDropBox/filterDropBoxShell/FilterDropBoxShell.module.scss
  components/Notices/filterDropBox/filterDropBoxShell/FilterDropBoxShell.tsx
  components/Notices/filterDropBox/filterTitle/FilterTitle.module.scss
  components/Notices/filterDropBox/hourlyPayInput/HourlyPayInput.module.scss
Labels: 디자인, 알바님

#125 Feat: 알바님/gnb-알림창 데이터 받아와 UI에 반영
  components/common/navBar/notificationItem/NotificationItem.module.scss
  components/common/navBar/notificationItem/NotificationItem.tsx
  components/common/navBar/notificationList/NotificationList.tsx
  lib/calculateTimeAgo.ts
  lib/getAlerts.ts
  lib/getFullDate.ts
  types/alertsType.ts
Labels: 기능, 알바님

#128 Feat: 공통/gnb-유저 타입에 따른 버튼과 로그아웃 버튼 클릭 시 해당 페이지로 이동
  components/common/navBar/NavBar.tsx
Labels: 기능, 공통

#122 Feat: 공고 카드 컴포넌트-클릭 시 유저 플로우에 맞게 페이지 이동
  components/noticeList/noticeCard/noticeCard.tsx
  components/noticeList/noticeCardList/NoticeCardList.tsx
  components/noticeList/noticeListLayout/NoticeListLayout.module.scss
  components/noticeList/noticeListLayout/NoticeListLayout.tsx
  components/shop/noticeCard/NoticeCard.tsx
  components/shop/noticeCardList/NoticeCardList.tsx
  pages/api/mockdata.ts
  styles/global.scss
Labels: 기능, 공통

#129 Feat: 공통/공고 카드 - 지난 공고 로직 추가
  components/noticeList/noticeCard/noticeCard.module.scss
  components/noticeList/noticeCard/noticeCard.tsx
  components/shop/noticeCard/NoticeCard.module.scss
  components/shop/noticeCard/NoticeCard.tsx
Labels: 기능, 공통

#135 Feat: 알바님/알림창-읽음처리 api
  components/common/input/Input.tsx
  components/common/navBar/NavBar.tsx
  components/common/navBar/notificationItem/NotificationItem.module.scss
  components/common/navBar/notificationItem/NotificationItem.tsx
  components/common/navBar/notificationList/NotificationList.module.scss
  components/common/navBar/notificationList/NotificationList.tsx
  public/images/circle_canceled.svg
  types/alertsType.ts
Labels: 기능, 디자인, 알바님

#134 Feat: 공고 카드 - 상황에 맞는 링크 이동
  components/noticeList/noticeCard/noticeCard.tsx
  components/noticeList/noticeCardList/NoticeCardList.tsx
  components/shop/myShopProfile/MyShopProfile.tsx
  components/shop/noticeCardList/NoticeCardList.tsx
Labels: 기능, 공통

#133 Feat : 알바님/공고상세 페이지 구현
  components/common/modal/Modal.tsx
  components/common/modal/warningConfirmModal/warningConfirmModal.module.scss
  components/common/modal/warningConfirmModal/warningConfirmModal.tsx
  pages/detail/[id].tsx
  styles/detail.module.scss
Labels: 기능, 알바님

#126 Feat: 사장님/가게정보편집 등록된 정보 수정하기 기능 구현
  components/common/SelectBox/SelectBoxDropDown.tsx
  components/common/SelectBox/example.tsx
  components/common/input/Input.module.scss
  components/common/input/Input.tsx
  components/common/modal/Modal.module.scss
  components/common/selectBox/SelectBox.module.scss
  components/register/shopInfo/shopInfoForm/FileInput.tsx
  components/register/shopInfo/shopInfoForm/Input.tsx
  components/register/shopInfo/shopInfoForm/SelectBox.tsx
  components/register/shopInfo/shopInfoForm/ShopInfoEdit.tsx
  components/register/shopInfo/shopInfoForm/ShopInfoRegister.tsx
  components/register/shopInfo/shopInfoForm/Textarea.tsx
  components/register/shopInfo/shopInfoForm/constants.ts
  components/register/shopInfo/shopInfoForm/shopInfoForm.module.scss
  components/register/shopInfo/shopInfoForm/shopInfoForm.tsx
  components/register/shopInfo/shopInfoForm/test.http
  components/register/shopInfo/shopInfoForm/type.ts
  components/register/shopInfo/shopInfoTitle/ShopInfoTitle.tsx
  components/shop/myShopProfile/MyShopProfile.tsx
  components/shop/shopPageLayout/ShopPageLayout.tsx
  contexts/AuthProvider.tsx
  pages/edit/index.tsx
  pages/shop/index.tsx
  pages/shopEdit/index.tsx
  pages/shopRegister/index.tsx
  test,.http
Labels: 기능, 사장님

#130 fix : 알바님/신청내역 시간, 시급, 색상 수정
  components/user/userApplication/UserApplication.tsx
  components/user/userApplication/UserApplications.module.scss
  components/user/userApplication/UserApplications.tsx
  components/user/userPageLayout/UserPageLayout.module.scss
Labels: 디자인, 알바님

#131 Fix : 로그인/회원가입 - 비밀번호 숨김 수정
  components/sign/signupForm/SignupForm.module.scss
  components/sign/signupForm/SignupForm.tsx
Labels: 기능, 디자인, 로그인

#132 알바님/등록수정모달
  components/common/input/Input.tsx
  components/register/userInfo/userInfoForm/UserInfoForm.module.scss
  components/register/userInfo/userInfoForm/UserInfoForm.tsx
  components/user/userEditLayout/UserEditLayout.tsx
  components/user/userPageLayout/UserPageLayout.tsx
Labels: 기능, 알바님

#161 Fix: 공고등록 API 오류 수정
  components/register/notice/NoticeRegister/usePostNotice.ts
  pages/shop/NoticeRegister.tsx
Labels: 사장님
